// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7YDmWDYJ9-pg6IBwz3EkMJu2er4CDtdw',
    appId: '1:126798382097:web:aa47ef807f2e4848021db0',
    messagingSenderId: '126798382097',
    projectId: 'globalchat-c1761',
    authDomain: 'globalchat-c1761.firebaseapp.com',
    storageBucket: 'globalchat-c1761.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMp9I7VLSfomQ4cvTlXPXEKrGVUJlXDyc',
    appId: '1:126798382097:android:7304b9dbeb057056021db0',
    messagingSenderId: '126798382097',
    projectId: 'globalchat-c1761',
    storageBucket: 'globalchat-c1761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDczfcNvMx0Th3rxMiWLA8ZSo_cdfI5Ot4',
    appId: '1:126798382097:ios:f6311fe0e23033ec021db0',
    messagingSenderId: '126798382097',
    projectId: 'globalchat-c1761',
    storageBucket: 'globalchat-c1761.appspot.com',
    iosBundleId: 'com.redwire.globalchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDczfcNvMx0Th3rxMiWLA8ZSo_cdfI5Ot4',
    appId: '1:126798382097:ios:f6311fe0e23033ec021db0',
    messagingSenderId: '126798382097',
    projectId: 'globalchat-c1761',
    storageBucket: 'globalchat-c1761.appspot.com',
    iosBundleId: 'com.redwire.globalchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7YDmWDYJ9-pg6IBwz3EkMJu2er4CDtdw',
    appId: '1:126798382097:web:489e8115579c0035021db0',
    messagingSenderId: '126798382097',
    projectId: 'globalchat-c1761',
    authDomain: 'globalchat-c1761.firebaseapp.com',
    storageBucket: 'globalchat-c1761.appspot.com',
  );

}